### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by zapalagrzegorz** [mmkepler/fcc-calculator#1]
Hey,
Once I asked for feedback on fcc forum to my calc, I was replied that it fails to make this correct: 
5 / 10 - 4 / 10. Unfortunately, the result is -0.35, while the correct i 0.1. 
Cheers

**Comment by mmkepler** [comment]
I tested my calculator against several others on code pen that were written for this project, and all returned "-.35". This project is based on a simple hand held calculator, not the kind you would have on your desktop. After not being able to reproduce your results on other projects I input "5/10-4/10" into the google search bar. Google actually showed me where it  did the math as (5\10) - (4\10). This is why you are getting an answer of "0.1" on the calculator you are testing it against. This project is set to do a mathematical operation every time a sign button or the equal button is pushed, not to use the order of operations like a more advanced calculator would. Thanks.
